//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfdLogFacturaXML
    {
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public int secuencia { get; set; }
        public string estado { get; set; }
        public string mensaje { get; set; }
        public string estadoActual { get; set; }
        public string mensajeEA { get; set; }
        public string noAprobacion { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public string idUsuario { get; set; }
        public System.DateTime fechaAnulacion { get; set; }
        public string idUsuarioAnulacion { get; set; }
        public string archivoXML { get; set; }
    }
}
