//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GBRAEntities : DbContext
    {
        public GBRAEntities()
            : base("name=GBRAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwCfdiTransaccionesDeVenta> vwCfdiTransaccionesDeVenta { get; set; }
        public virtual DbSet<vwCfdiGeneraDocumentoDeVentaBRA> vwCfdiGeneraDocumentoDeVentaBRA { get; set; }
        public virtual DbSet<cfdLogFacturaXML> cfdLogFacturaXML { get; set; }
    
        public virtual int spCfdiActualizaNumeroFiscalElectronico(Nullable<short> sOPTYPE, string nUMFAC, string sERNUM, ObjectParameter mENS)
        {
            var sOPTYPEParameter = sOPTYPE.HasValue ?
                new ObjectParameter("SOPTYPE", sOPTYPE) :
                new ObjectParameter("SOPTYPE", typeof(short));
    
            var nUMFACParameter = nUMFAC != null ?
                new ObjectParameter("NUMFAC", nUMFAC) :
                new ObjectParameter("NUMFAC", typeof(string));
    
            var sERNUMParameter = sERNUM != null ?
                new ObjectParameter("SERNUM", sERNUM) :
                new ObjectParameter("SERNUM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCfdiActualizaNumeroFiscalElectronico", sOPTYPEParameter, nUMFACParameter, sERNUMParameter, mENS);
        }
    }
}
