//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiTransaccionesDeVenta
    {
        public string estadoContabilizado { get; set; }
        public short soptype { get; set; }
        public string docid { get; set; }
        public string sopnumbe { get; set; }
        public Nullable<System.DateTime> fechahora { get; set; }
        public string CUSTNMBR { get; set; }
        public string nombreCliente { get; set; }
        public string idImpuestoCliente { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> montoActualOriginal { get; set; }
        public Nullable<short> voidstts { get; set; }
        public string estado { get; set; }
        public string mensaje { get; set; }
        public string comprobanteXml { get; set; }
        public string ID_Certificado { get; set; }
        public string ruta_certificado { get; set; }
        public string ruta_clave { get; set; }
        public string contrasenia_clave { get; set; }
        public string ruta_certificadoPac { get; set; }
        public string ruta_clavePac { get; set; }
        public string contrasenia_clavePac { get; set; }
        public string rfc { get; set; }
        public string regimen { get; set; }
        public string rutaXml { get; set; }
        public string codigoPostal { get; set; }
        public string estadoActual { get; set; }
        public string mensajeEA { get; set; }
        public string isocurrc { get; set; }
        public Nullable<int> addenda { get; set; }
    }
}
