//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiGeneraDocumentoDeVentaBRA
    {
        public string correlativo { get; set; }
        public short soptype { get; set; }
        public string SOPNUMBE { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public string emisorTipoDoc { get; set; }
        public string emisorNroDoc { get; set; }
        public string emisorNombre { get; set; }
        public string InscricaoPrestador { get; set; }
        public string TipoRPS { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public string horaEmision { get; set; }
        public string StatusRPS { get; set; }
        public string TributacaoRPS { get; set; }
        public decimal montoTotalVenta { get; set; }
        public decimal descuentoGlobalMonto { get; set; }
        public Nullable<decimal> ValorPIS { get; set; }
        public Nullable<decimal> ValorCOFINS { get; set; }
        public Nullable<decimal> ValorINSS { get; set; }
        public Nullable<decimal> ValorIR { get; set; }
        public Nullable<decimal> ValorCSLL { get; set; }
        public string CodigoServico { get; set; }
        public string AliquotaServicos { get; set; }
        public string ISSRetido { get; set; }
        public string CPFCNPJTomador { get; set; }
        public string InscricaoMunicipalTomador { get; set; }
        public string InscricaoEstadualTomador { get; set; }
        public string RazaoSocialTomador { get; set; }
        public string Emisor_TipoLogradouro { get; set; }
        public string Emisor_Logradouro { get; set; }
        public string Emisor_NumeroEndereco { get; set; }
        public string Emisor_Bairro { get; set; }
        public string Emisor_Cidade { get; set; }
        public string Emisor_CEP { get; set; }
        public string Emisor_UF { get; set; }
        public string EmailTomador { get; set; }
        public string Concepto { get; set; }
        public int ValorCargaTributaria { get; set; }
        public int PercentualCargaTributaria { get; set; }
        public string FonteCargaTributaria { get; set; }
        public decimal ValorTotalRecebido { get; set; }
    }
}
