//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prefeitura.WService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="WService.LoteNFeSoap")]
    public interface LoteNFeSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (EnvioRPSRequest) of message EnvioRPSRequest does not match the default value (EnvioRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        Prefeitura.WService.EnvioRPSResponse EnvioRPS(Prefeitura.WService.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.EnvioRPSResponse> EnvioRPSAsync(Prefeitura.WService.EnvioRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (EnvioLoteRPSRequest) of message EnvioLoteRPSRequest does not match the default value (EnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        Prefeitura.WService.EnvioLoteRPSResponse EnvioLoteRPS(Prefeitura.WService.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(Prefeitura.WService.EnvioLoteRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (TesteEnvioLoteRPSRequest) of message TesteEnvioLoteRPSRequest does not match the default value (TesteEnvioLoteRPS)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        Prefeitura.WService.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(Prefeitura.WService.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(Prefeitura.WService.TesteEnvioLoteRPSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CancelamentoNFeRequest) of message CancelamentoNFeRequest does not match the default value (CancelamentoNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        Prefeitura.WService.CancelamentoNFeResponse CancelamentoNFe(Prefeitura.WService.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.CancelamentoNFeResponse> CancelamentoNFeAsync(Prefeitura.WService.CancelamentoNFeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeRequest) of message ConsultaNFeRequest does not match the default value (ConsultaNFe)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        Prefeitura.WService.ConsultaNFeResponse ConsultaNFe(Prefeitura.WService.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeResponse> ConsultaNFeAsync(Prefeitura.WService.ConsultaNFeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeRecebidasRequest) of message ConsultaNFeRecebidasRequest does not match the default value (ConsultaNFeRecebidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        Prefeitura.WService.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(Prefeitura.WService.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(Prefeitura.WService.ConsultaNFeRecebidasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaNFeEmitidasRequest) of message ConsultaNFeEmitidasRequest does not match the default value (ConsultaNFeEmitidas)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        Prefeitura.WService.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(Prefeitura.WService.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(Prefeitura.WService.ConsultaNFeEmitidasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaLoteRequest) of message ConsultaLoteRequest does not match the default value (ConsultaLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        Prefeitura.WService.ConsultaLoteResponse ConsultaLote(Prefeitura.WService.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaLoteResponse> ConsultaLoteAsync(Prefeitura.WService.ConsultaLoteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaInformacoesLoteRequest) of message ConsultaInformacoesLoteRequest does not match the default value (ConsultaInformacoesLote)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        Prefeitura.WService.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(Prefeitura.WService.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(Prefeitura.WService.ConsultaInformacoesLoteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaCNPJRequest) of message ConsultaCNPJRequest does not match the default value (ConsultaCNPJ)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        Prefeitura.WService.ConsultaCNPJResponse ConsultaCNPJ(Prefeitura.WService.ConsultaCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaCNPJResponse> ConsultaCNPJAsync(Prefeitura.WService.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest() {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse() {
        }
        
        public EnvioRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest() {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse() {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest() {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse() {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest() {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse() {
        }
        
        public CancelamentoNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest() {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse() {
        }
        
        public ConsultaNFeResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest() {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse() {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest() {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse() {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest() {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse() {
        }
        
        public ConsultaLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest() {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse() {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest() {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse() {
        }
        
        public ConsultaCNPJResponse(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoteNFeSoapChannel : Prefeitura.WService.LoteNFeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<Prefeitura.WService.LoteNFeSoap>, Prefeitura.WService.LoteNFeSoap {
        
        public LoteNFeSoapClient() {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.EnvioRPSResponse Prefeitura.WService.LoteNFeSoap.EnvioRPS(Prefeitura.WService.EnvioRPSRequest request) {
            return base.Channel.EnvioRPS(request);
        }
        
        public string EnvioRPS(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.EnvioRPSRequest inValue = new Prefeitura.WService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.EnvioRPSResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).EnvioRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.EnvioRPSResponse> Prefeitura.WService.LoteNFeSoap.EnvioRPSAsync(Prefeitura.WService.EnvioRPSRequest request) {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.EnvioRPSRequest inValue = new Prefeitura.WService.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.EnvioLoteRPSResponse Prefeitura.WService.LoteNFeSoap.EnvioLoteRPS(Prefeitura.WService.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public string EnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.EnvioLoteRPSRequest inValue = new Prefeitura.WService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.EnvioLoteRPSResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).EnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.EnvioLoteRPSResponse> Prefeitura.WService.LoteNFeSoap.EnvioLoteRPSAsync(Prefeitura.WService.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.EnvioLoteRPSRequest inValue = new Prefeitura.WService.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.TesteEnvioLoteRPSResponse Prefeitura.WService.LoteNFeSoap.TesteEnvioLoteRPS(Prefeitura.WService.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public string TesteEnvioLoteRPS(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.TesteEnvioLoteRPSRequest inValue = new Prefeitura.WService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.TesteEnvioLoteRPSResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).TesteEnvioLoteRPS(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.TesteEnvioLoteRPSResponse> Prefeitura.WService.LoteNFeSoap.TesteEnvioLoteRPSAsync(Prefeitura.WService.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.TesteEnvioLoteRPSRequest inValue = new Prefeitura.WService.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.CancelamentoNFeResponse Prefeitura.WService.LoteNFeSoap.CancelamentoNFe(Prefeitura.WService.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public string CancelamentoNFe(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.CancelamentoNFeRequest inValue = new Prefeitura.WService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.CancelamentoNFeResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).CancelamentoNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.CancelamentoNFeResponse> Prefeitura.WService.LoteNFeSoap.CancelamentoNFeAsync(Prefeitura.WService.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.CancelamentoNFeRequest inValue = new Prefeitura.WService.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaNFeResponse Prefeitura.WService.LoteNFeSoap.ConsultaNFe(Prefeitura.WService.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFe(request);
        }
        
        public string ConsultaNFe(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeRequest inValue = new Prefeitura.WService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaNFeResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFe(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeResponse> Prefeitura.WService.LoteNFeSoap.ConsultaNFeAsync(Prefeitura.WService.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeRequest inValue = new Prefeitura.WService.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaNFeRecebidasResponse Prefeitura.WService.LoteNFeSoap.ConsultaNFeRecebidas(Prefeitura.WService.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public string ConsultaNFeRecebidas(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeRecebidasRequest inValue = new Prefeitura.WService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaNFeRecebidasResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFeRecebidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeRecebidasResponse> Prefeitura.WService.LoteNFeSoap.ConsultaNFeRecebidasAsync(Prefeitura.WService.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeRecebidasRequest inValue = new Prefeitura.WService.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaNFeEmitidasResponse Prefeitura.WService.LoteNFeSoap.ConsultaNFeEmitidas(Prefeitura.WService.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public string ConsultaNFeEmitidas(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeEmitidasRequest inValue = new Prefeitura.WService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaNFeEmitidasResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFeEmitidas(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeEmitidasResponse> Prefeitura.WService.LoteNFeSoap.ConsultaNFeEmitidasAsync(Prefeitura.WService.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaNFeEmitidasRequest inValue = new Prefeitura.WService.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaLoteResponse Prefeitura.WService.LoteNFeSoap.ConsultaLote(Prefeitura.WService.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLote(request);
        }
        
        public string ConsultaLote(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaLoteRequest inValue = new Prefeitura.WService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaLoteResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaLoteResponse> Prefeitura.WService.LoteNFeSoap.ConsultaLoteAsync(Prefeitura.WService.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaLoteRequest inValue = new Prefeitura.WService.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaInformacoesLoteResponse Prefeitura.WService.LoteNFeSoap.ConsultaInformacoesLote(Prefeitura.WService.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public string ConsultaInformacoesLote(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaInformacoesLoteRequest inValue = new Prefeitura.WService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaInformacoesLoteResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaInformacoesLote(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaInformacoesLoteResponse> Prefeitura.WService.LoteNFeSoap.ConsultaInformacoesLoteAsync(Prefeitura.WService.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaInformacoesLoteRequest inValue = new Prefeitura.WService.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prefeitura.WService.ConsultaCNPJResponse Prefeitura.WService.LoteNFeSoap.ConsultaCNPJ(Prefeitura.WService.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJ(request);
        }
        
        public string ConsultaCNPJ(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaCNPJRequest inValue = new Prefeitura.WService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            Prefeitura.WService.ConsultaCNPJResponse retVal = ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaCNPJ(inValue);
            return retVal.RetornoXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prefeitura.WService.ConsultaCNPJResponse> Prefeitura.WService.LoteNFeSoap.ConsultaCNPJAsync(Prefeitura.WService.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prefeitura.WService.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML) {
            Prefeitura.WService.ConsultaCNPJRequest inValue = new Prefeitura.WService.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((Prefeitura.WService.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
    }
}
